import type { Metadata } from "next";
import { Inter } from 'next/font/google';
import "./globals.css";

const Inter_init = Inter({
  subsets: ['latin'],
  weight: ['100', '200', '300', '500', '600','700'],
  variable: '--font-Inter',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={Inter_init.variable}>
        {children}
      </body>
    </html>
  );
}